import{lazy,Suspense,useEffect,useMemo,useState}from'react'
import{appUrl,loadBottomSnapshot,loadChart,unifiedTickerUrl,type BottomRow,type BottomSnapshot,type ChartBar}from'./data'
import{useOwner,type Drawing}from'./owner'
import{bottomPresets,findBottomPreset}from'./presets'

type View='overview'|'screener'|'setups'|'stages'|'groups'|'watchlist'|'screens'|'alerts'|'detail'
const views:{id:View;label:string}[]=[{id:'overview',label:'Overview'},{id:'screener',label:'Screener'},{id:'setups',label:'Setup lenses'},{id:'stages',label:'Stages'},{id:'groups',label:'Groups'},{id:'watchlist',label:'Watchlist'},{id:'screens',label:'Saved screens'},{id:'alerts',label:'Alerts'}]
const Chart=lazy(()=>import('./Chart'))
const n=(value:unknown,fallback=0)=>Number.isFinite(Number(value))?Number(value):fallback
const fmt=(value:unknown,digits=1)=>Number.isFinite(Number(value))?Number(value).toFixed(digits):'—'
const setup=(row:BottomRow)=>String(row.primarySetup??row.setup??row.setupTags?.[0]??'Other')
const text=(value:unknown)=>String(value??'').replaceAll('_',' ')
const params=()=>new URLSearchParams(location.search)
const initialView=():View=>{const value=params().get('view')as View;return[...views.map(item=>item.id),'detail'].includes(value)?value:'overview'}

export default function App(){
  const owner=useOwner(),[snapshot,setSnapshot]=useState<BottomSnapshot|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[view,setViewState]=useState<View>(initialView),[query,setQuery]=useState(params().get('q')??''),[preset,setPreset]=useState(params().get('preset')??params().get('screen')??''),[setupFilter,setSetupFilter]=useState(params().get('setup')??''),[stageFilter,setStageFilter]=useState(params().get('stage')??''),[groupFilter,setGroupFilter]=useState(params().get('group')??''),[sort,setSort]=useState(params().get('sort')??'score'),[ticker,setTicker]=useState(params().get('ticker')??''),[chart,setChart]=useState<ChartBar[]>([]),[chartError,setChartError]=useState(''),[interval,setInterval]=useState<'D'|'W'>('W'),[drawings,setDrawings]=useState<Drawing[]>([]),[message,setMessage]=useState(''),[screenDialog,setScreenDialog]=useState(false),[screenName,setScreenName]=useState('')
  const reload=()=>{setLoading(true);setError('');loadBottomSnapshot().then(value=>{setSnapshot(value);if(!ticker&&value.rows[0])setTicker(value.rows[0].ticker)}).catch(reason=>setError(String(reason.message??reason))).finally(()=>setLoading(false))}
  useEffect(reload,[])
  useEffect(()=>{history.replaceState(null,'',appUrl({view,ticker:view==='detail'?ticker:undefined,q:query||undefined,preset:preset||undefined,setup:setupFilter||undefined,stage:stageFilter||undefined,group:groupFilter||undefined,sort}))},[view,ticker,query,preset,setupFilter,stageFilter,groupFilter,sort])
  const setView=(next:View,extra:Record<string,string>={})=>{setViewState(next);const url=appUrl({view:next,ticker:next==='detail'?ticker:undefined,q:query||undefined,preset:preset||undefined,setup:setupFilter||undefined,stage:stageFilter||undefined,group:groupFilter||undefined,sort,...extra});history.replaceState(null,'',url);scrollTo({top:0,behavior:'smooth'})}
  useEffect(()=>{if(view!=='detail'||!ticker||!snapshot)return;let live=true;setChart([]);setChartError('');loadChart(snapshot.manifest,ticker).then(rows=>{if(live)setChart(rows)}).catch(reason=>{if(live)setChartError(String(reason.message??reason))});owner.listDrawings(ticker).then(rows=>{if(live)setDrawings(rows)}).catch(()=>{if(live)setDrawings([])});return()=>{live=false}},[view,ticker,snapshot?.manifest.runId,owner.user?.id])
  const rows=useMemo(()=>{
    const source=view==='watchlist'?snapshot?.rows.filter(row=>owner.watchlist.includes(row.ticker))??[]:snapshot?.rows??[],needle=query.trim().toLowerCase(),activePreset=findBottomPreset(preset)
    return source.filter(row=>(!activePreset||activePreset.match(row))&&(!needle||row.ticker.toLowerCase().includes(needle)||setup(row).toLowerCase().includes(needle)||text(row.industry).toLowerCase().includes(needle))&&(!setupFilter||(row.setupTags??[]).includes(setupFilter)||setup(row)===setupFilter)&&(!stageFilter||String(row.stage)===stageFilter)&&(!groupFilter||row.sector===groupFilter||row.industry===groupFilter)).sort((a,b)=>sort==='rs'?n(b.rsRank)-n(a.rsRank):sort==='risk'?n(a.entryRiskPct,999)-n(b.entryRiskPct,999):sort==='volume'?n(b.volumeRatio)-n(a.volumeRatio):n(b.focusBlend??b.score)-n(a.focusBlend??a.score))
  },[snapshot?.rows,view,owner.watchlist,query,preset,setupFilter,stageFilter,groupFilter,sort])
  const selected=snapshot?.rows.find(row=>row.ticker===ticker)
  const navigateTicker=(row:BottomRow)=>{setTicker(row.ticker);setViewState('detail');history.replaceState(null,'',appUrl({view:'detail',ticker:row.ticker}))}
  const reset=()=>{setQuery('');setPreset('');setSetupFilter('');setStageFilter('');setGroupFilter('');history.replaceState(null,'',appUrl({view:'screener',sort}))}
  const exportCsv=()=>{const fields=['ticker','focusBlend','tradeStatus','actionability','primarySetup','stage','rsRank','baseScore','volumeRatio','entryRiskPct'],body=[fields.join(','),...rows.map(row=>fields.map(field=>JSON.stringify(row[field]??'')).join(','))].join('\n'),link=document.createElement('a');link.href=URL.createObjectURL(new Blob([body],{type:'text/csv'}));link.download=`bottom-fishing-${snapshot?.manifest.sessionDate??'scan'}.csv`;link.click();URL.revokeObjectURL(link.href)}
  const saveScreen=async()=>{if(!screenName.trim())return;try{await owner.saveScreen(screenName,{query,preset,setup:setupFilter,stage:stageFilter,group:groupFilter,sort});setMessage('Screen synced.');setScreenDialog(false);setScreenName('')}catch(reason){setMessage(String((reason as Error).message??reason))}}
  if(loading)return<div className="bf-state"><div className="bf-spinner"/><b>Opening immutable Bottom run…</b></div>
  if(error||!snapshot)return<div className="bf-state error"><b>Bottom Fishing could not open</b><p>{error}</p><button onClick={reload}>Retry</button></div>
  return<div className="bf-app">
    <header className="bf-header"><div className="bf-brand"><span>BF</span><div><b>StockScout Bottom Fishing</b><small>FULL RESPONSIVE PWA · EOD</small></div></div><div className="bf-integrity"><b>Verified</b><span>{snapshot.manifest.sessionDate} · {snapshot.activation.runId}</span><em className={snapshot.sidecarStatus}>{snapshot.sidecarStatus==='verified'?'Full source fields':'Core fields'}</em></div><div className="bf-owner">{owner.user?<><span>{owner.user.email}</span><button onClick={()=>void owner.signOut()}>Sign out</button></>:<button className="primary" disabled={owner.loading} onClick={()=>void owner.signIn()}>Owner sign in with Google</button>}{owner.error?<small>{owner.error}</small>:null}</div></header>
    <nav className="bf-nav" aria-label="Main views">{views.map(item=><button key={item.id} className={view===item.id?'active':''} onClick={()=>setView(item.id)}>{item.label}{item.id==='watchlist'?<b>{owner.watchlist.length}</b>:item.id==='alerts'?<b>{owner.alerts.length}</b>:null}</button>)}</nav>
    {message?<div className="bf-message" role="status">{message}<button onClick={()=>setMessage('')}>×</button></div>:null}
    {view==='overview'?<Overview snapshot={snapshot} onTicker={navigateTicker} onView={setView}/>:null}
    {['screener','watchlist'].includes(view)?<><Toolbar query={query} setQuery={setQuery} preset={preset} setPreset={setPreset} setupFilter={setupFilter} setSetup={setSetupFilter} stageFilter={stageFilter} setStage={setStageFilter} sort={sort} setSort={setSort} rows={snapshot.rows} reset={reset} exportCsv={exportCsv} saveScreen={()=>setScreenDialog(true)} canSave={Boolean(owner.user)}/><Screener rows={rows} watchlist={owner.watchlist} onWatch={ticker=>void owner.toggleWatch(ticker).catch(reason=>setMessage(String(reason.message??reason)))} canWatch={Boolean(owner.user)} onTicker={navigateTicker}/></>:null}
    {view==='setups'?<SetupView rows={snapshot.rows} onSelect={value=>{setSetupFilter(value);setView('screener',{setup:value})}}/>:null}
    {view==='stages'?<StageView rows={snapshot.rows} onSelect={value=>{setStageFilter(value);setView('screener',{stage:value})}}/>:null}
    {view==='groups'?<GroupsView rows={snapshot.rows} onSelect={value=>{setGroupFilter(value);setView('screener',{group:value})}}/>:null}
    {view==='screens'?<Screens onApply={definition=>{setQuery(String(definition.query??''));setPreset(String(definition.preset??''));setSetupFilter(String(definition.setup??''));setStageFilter(String(definition.stage??''));setGroupFilter(String(definition.group??''));setSort(String(definition.sort??'score'));setView('screener')}}/>:null}
    {view==='alerts'?<Alerts/>:null}
    {view==='detail'&&selected?<Detail row={selected} chart={chart} chartError={chartError} interval={interval} setInterval={setInterval} drawings={drawings} runId={snapshot.activation.runId} watched={owner.watchlist.includes(selected.ticker)} canWatch={Boolean(owner.user)} onWatch={()=>void owner.toggleWatch(selected.ticker).catch(reason=>setMessage(String(reason.message??reason)))}/>:null}
    {screenDialog?<div className="bf-dialog-backdrop" role="presentation"><form className="bf-dialog" role="dialog" aria-modal="true" aria-label="Save current screen" onSubmit={event=>{event.preventDefault();void saveScreen()}}><b>Save current screen</b><p>The current filters and sort will sync to Unified.</p><label>Name<input autoFocus required maxLength={80} value={screenName} onChange={event=>setScreenName(event.target.value)}/></label><div><button type="button" onClick={()=>setScreenDialog(false)}>Cancel</button><button type="submit">Save screen</button></div></form></div>:null}
    <footer>Same immutable Bottom data as <a href="https://garrincha077.github.io/StockScout-Unified/?mode=bottom-fishing">StockScout Unified</a>. Scores and prices are EOD context, not live.</footer>
  </div>
}

function Overview({snapshot,onTicker,onView}:{snapshot:BottomSnapshot;onTicker:(row:BottomRow)=>void;onView:(view:View)=>void}){const actionable=snapshot.rows.filter(row=>row.actionability==='actionable_now').length,entry=snapshot.rows.filter(row=>row.tradeStatus==='entry_ready').length,stage2=snapshot.rows.filter(row=>row.stage===2).length;return<main className="bf-main"><section className="bf-hero"><div><small>ACTIVE IMMUTABLE RUN</small><h1>Bottom Fishing cockpit</h1><p>Full detector context without duplicating a scan or changing a score.</p></div><button onClick={()=>onView('screener')}>Explore {snapshot.rows.length.toLocaleString()} candidates →</button></section><section className="bf-metrics"><Metric label="Candidates" value={snapshot.manifest.counts.candidates}/><Metric label="Actionable now" value={actionable}/><Metric label="Entry ready" value={entry}/><Metric label="Stage 2" value={stage2}/><Metric label="Chart coverage" value={`${fmt(snapshot.manifest.health?.coveragePct,1)}%`}/></section><section className="bf-panel"><header><div><b>Highest published Bottom context</b><span>Original mode order and scores</span></div><button onClick={()=>onView('screener')}>Full Screener</button></header><div className="bf-top-grid">{snapshot.rows.slice(0,8).map(row=><button key={row.ticker} onClick={()=>onTicker(row)}><b>{row.ticker}</b><strong>{fmt(row.focusBlend??row.score)}</strong><span>{setup(row)}</span><small>RS {fmt(row.rsRank,0)} · {text(row.tradeStatus)}</small></button>)}</div></section></main>}
function Metric({label,value}:{label:string;value:string|number}){return<div><span>{label}</span><b>{value}</b></div>}

function Toolbar({query,setQuery,preset,setPreset,setupFilter,setSetup,stageFilter,setStage,sort,setSort,rows,reset,exportCsv,saveScreen,canSave}:{query:string;setQuery:(v:string)=>void;preset:string;setPreset:(v:string)=>void;setupFilter:string;setSetup:(v:string)=>void;stageFilter:string;setStage:(v:string)=>void;sort:string;setSort:(v:string)=>void;rows:BottomRow[];reset:()=>void;exportCsv:()=>void;saveScreen:()=>void;canSave:boolean}){const setups=[...new Set(rows.flatMap(row=>row.setupTags??[setup(row)]))].sort();return<section className="bf-toolbar"><input aria-label="Search candidates" placeholder="Ticker, setup, industry…" value={query} onChange={event=>setQuery(event.target.value)}/><select aria-label="Original Bottom preset" value={preset} onChange={event=>setPreset(event.target.value)}><option value="">All 19 strategy presets</option>{bottomPresets.map(item=><option key={item.name}>{item.name}</option>)}</select><select aria-label="Setup lens" value={setupFilter} onChange={event=>setSetup(event.target.value)}><option value="">All setups</option>{setups.map(value=><option key={value}>{value}</option>)}</select><select aria-label="Stage" value={stageFilter} onChange={event=>setStage(event.target.value)}><option value="">All stages</option>{[1,2,3,4].map(value=><option key={value} value={value}>Stage {value}</option>)}</select><select aria-label="Sort" value={sort} onChange={event=>setSort(event.target.value)}><option value="score">Bottom score</option><option value="rs">RS rating</option><option value="risk">Entry risk</option><option value="volume">RVOL</option></select><button onClick={reset}>Reset</button><button onClick={exportCsv}>CSV</button><button disabled={!canSave} onClick={saveScreen}>Save screen</button></section>}

function Screener({rows,watchlist,onWatch,canWatch,onTicker}:{rows:BottomRow[];watchlist:string[];onWatch:(ticker:string)=>void;canWatch:boolean;onTicker:(row:BottomRow)=>void}){const[limit,setLimit]=useState(200);useEffect(()=>setLimit(200),[rows]);const visible=rows.slice(0,limit);return<main className="bf-table-panel"><header><b>{rows.length.toLocaleString()} matches</b><span>Showing {visible.length.toLocaleString()} · click a row for chart and detector detail</span></header><div className="bf-table-scroll"><table><thead><tr><th/><th>Ticker</th><th>Score</th><th>Trade status</th><th>Trigger</th><th>Entry risk</th><th>Actionability</th><th>Setup</th><th>Stage</th><th>RS</th><th>Base</th><th>RVOL</th><th>To trigger</th></tr></thead><tbody>{visible.map(row=>{const trigger=n(row.tradePlan?.triggerReferenceLevel,NaN),distance=Number.isFinite(trigger)&&trigger?((n(row.price)-trigger)/trigger*100):NaN;return<tr key={row.ticker} onClick={()=>onTicker(row)}><td><button aria-label={`${watchlist.includes(row.ticker)?'Remove':'Add'} ${row.ticker} ${watchlist.includes(row.ticker)?'from':'to'} watchlist`} className={watchlist.includes(row.ticker)?'star on':'star'} disabled={!canWatch} onClick={event=>{event.stopPropagation();onWatch(row.ticker)}}>★</button></td><td><b>{row.ticker}</b></td><td><strong>{fmt(row.focusBlend??row.score)}</strong></td><td><span className={`badge ${row.tradeStatus}`}>{text(row.tradeStatus)}</span></td><td>{text(row.tradePlan?.triggerState)}</td><td>{fmt(row.entryRiskPct)}%</td><td>{text(row.actionability)}</td><td>{setup(row)}</td><td>{row.stage} · {row.stageName}</td><td>{fmt(row.rsRank,0)}</td><td>{fmt(row.baseScore,0)}</td><td>{fmt(row.volumeRatio,2)}x</td><td>{Number.isFinite(distance)?`${distance>0?'+':''}${distance.toFixed(1)}%`:'—'}</td></tr>})}</tbody></table>{visible.length<rows.length?<button className="bf-load-more" onClick={()=>setLimit(value=>value+200)}>Load 200 more</button>:null}</div></main>}

function SetupView({rows,onSelect}:{rows:BottomRow[];onSelect:(value:string)=>void}){const map=new Map<string,BottomRow[]>();for(const row of rows)for(const tag of row.setupTags??[setup(row)])map.set(tag,[...(map.get(tag)??[]),row]);return<CardGrid title="Setup lenses" subtitle="Every source detector remains independent; choosing a lens only filters." items={[...map].sort((a,b)=>b[1].length-a[1].length).map(([name,matches])=>({name,count:matches.length,detail:`Top ${matches[0]?.ticker??'—'} · avg RS ${fmt(matches.reduce((sum,row)=>sum+n(row.rsRank),0)/matches.length,0)}`}))} onSelect={onSelect}/>}
function StageView({rows,onSelect}:{rows:BottomRow[];onSelect:(value:string)=>void}){return<CardGrid title="Stage map" subtitle="Published stage and substage context." items={[1,2,3,4].map(stage=>{const matches=rows.filter(row=>row.stage===stage);return{name:String(stage),label:`Stage ${stage}`,count:matches.length,detail:`${matches.filter(row=>row.actionability==='actionable_now').length} actionable`}})} onSelect={onSelect}/>}
function GroupsView({rows,onSelect}:{rows:BottomRow[];onSelect:(value:string)=>void}){const counts=new Map<string,number>();for(const row of rows)for(const group of[row.sector,row.industry])if(group)counts.set(group,(counts.get(group)??0)+1);return<CardGrid title="Sector & industry groups" subtitle="Open a complete group in the Screener." items={[...counts].sort((a,b)=>b[1]-a[1]).map(([name,count])=>({name,count,detail:rows.find(row=>row.sector===name)?'Sector':'Industry'}))} onSelect={onSelect}/>}
function CardGrid({title,subtitle,items,onSelect}:{title:string;subtitle:string;items:Array<{name:string;label?:string;count:number;detail:string}>;onSelect:(value:string)=>void}){return<main className="bf-main"><section className="bf-panel"><header><div><b>{title}</b><span>{subtitle}</span></div></header><div className="bf-card-grid">{items.map(item=><button key={item.name} onClick={()=>onSelect(item.name)}><b>{item.label??text(item.name)}</b><strong>{item.count}</strong><span>{item.detail}</span></button>)}</div></section></main>}

function Screens({onApply}:{onApply:(value:Record<string,unknown>)=>void}){const owner=useOwner();if(!owner.user)return<Gate/>;return<main className="bf-main"><section className="bf-panel"><header><div><b>Saved screens</b><span>Private and synced with Unified.</span></div></header><div className="bf-owner-list">{owner.screens.map(screen=><article key={screen.id}><div><b>{screen.name}</b><span>{Object.entries(screen.definition).filter(([,v])=>v).map(([k,v])=>`${k}: ${v}`).join(' · ')||'No filters'}</span></div><button onClick={()=>onApply(screen.definition)}>Apply</button><button onClick={()=>void owner.deleteScreen(screen.id)}>Delete</button></article>)}{!owner.screens.length?<p>No saved Bottom screens.</p>:null}</div></section></main>}
function alertStatus(alert:any,state:any){if(!alert.enabled)return'Paused';if(state?.error)return'Stale';if(state?.last_condition&&!state.armed)return'Triggered';if(state?.current_price!=null&&state.current_level!=null&&Math.abs(state.current_price-state.current_level)/Math.max(.01,Math.abs(state.current_level))<=.01)return'Near';return'Armed'}
function Alerts(){const owner=useOwner();if(!owner.user)return<Gate/>;return<main className="bf-main"><section className="bf-panel"><header><div><b>Drawing-first Alerts Center</b><span>Runtime state shared with Unified · evaluated after verified EOD.</span></div></header><div className="bf-owner-list">{owner.alerts.map(alert=>{const state=owner.states.find(item=>item.alert_id===alert.id),status=alertStatus(alert,state);return<article key={alert.id}><div><b>{alert.name} · {alert.ticker??'market'}</b><span>{text(alert.payload.kind)} · {text(alert.payload.condition??alert.payload.operator)} · {status}</span><small>{state?.evaluated_at?`Evaluated ${new Date(state.evaluated_at).toLocaleString()} · ${state.last_run_id}`:'Not evaluated yet'}</small></div></article>})}{!owner.alerts.length?<p>No Bottom alerts.</p>:null}</div></section></main>}
function Gate(){const owner=useOwner();return<main className="bf-state"><b>Owner sign-in required</b><p>Watchlists, screens, drawings and alerts stay private.</p><button onClick={()=>void owner.signIn()}>Sign in with Google</button></main>}

function Detail({row,chart,chartError,interval,setInterval,drawings,runId,watched,canWatch,onWatch}:{row:BottomRow;chart:ChartBar[];chartError:string;interval:'D'|'W';setInterval:(value:'D'|'W')=>void;drawings:Drawing[];runId:string;watched:boolean;canWatch:boolean;onWatch:()=>void}){const plan=row.tradePlan??{};return<main className="bf-detail"><section className="bf-detail-head"><button aria-label={`${watched?'Remove from':'Add to'} watchlist`} className={watched?'star on':'star'} disabled={!canWatch} onClick={onWatch}>★</button><div><h1>{row.ticker}</h1><span>{setup(row)} · Stage {row.stage} {row.stageName}</span></div><strong>{fmt(row.focusBlend??row.score)}</strong><b>${fmt(row.price,2)}</b><a href={unifiedTickerUrl(row.ticker,runId)}>Open in Unified ↗</a></section><section className="bf-chart-panel"><header><div><button className={interval==='D'?'active':''} onClick={()=>setInterval('D')}>Daily</button><button className={interval==='W'?'active':''} onClick={()=>setInterval('W')}>Weekly</button></div><span>{drawings.length} synced drawing{drawings.length===1?'':'s'} · shared UTC anchors</span></header>{chart.length?<Suspense fallback={<div className="bf-chart-state">Loading chart engine…</div>}><Chart bars={chart} interval={interval} drawings={drawings}/></Suspense>:<div className="bf-chart-state">{chartError||'Loading verified chart…'}</div>}</section><section className="bf-detail-grid"><DetailCard title="Trade readiness" values={[['Status',text(row.tradeStatus)],['Trigger state',text(plan.triggerState)],['Entry trigger',fmt(plan.triggerReferenceLevel,2)],['Entry risk',`${fmt(row.entryRiskPct)}%`]]}/><DetailCard title="Setup quality" values={[['Primary',setup(row)],['Base score',fmt(row.baseScore,0)],['Base weeks',fmt(row.baseWeeks,0)],['Base depth',`${fmt(row.baseDepthPct)}%`]]}/><DetailCard title="Relative strength" values={[['RS rating',fmt(row.rsRank,0)],['RS 3M',`${fmt(row.rs3m)}%`],['RS 6M',`${fmt(row.rs6m)}%`],['52W high distance',`${fmt(row.from52wHigh)}%`]]}/><DetailCard title="Launch context" values={[['RVOL',`${fmt(row.volumeRatio,2)}x`],['EMA stack',fmt(row.emaStackLaunchScore,0)],['Accumulation',fmt(row.accumulationScore,0)],['MA cluster',fmt(row.maClusterScore,0)]]}/></section></main>}
function DetailCard({title,values}:{title:string;values:Array<[string,string]>}){return<article><b>{title}</b><dl>{values.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></article>}
